parameters:
    _user: Ds\Bundle\UserBundle\Entity\User

ds_security:
    permissions:
        user:               { title: User,          entity: '%_user%',              attributes: [BROWSE, READ, EDIT, ADD, DELETE] }
        user_field:         { title: All Fields,    field:  '%_user%.*',            attributes: [BROWSE, READ, EDIT] }
        user_id:            { title: ID,            field:  '%_user%.id',           attributes: [BROWSE, READ, EDIT] }
        user_uuid:          { title: UUID,          field:  '%_user%.uuid',         attributes: [BROWSE, READ, EDIT] }
        user_created_at:    { title: Created At,    field:  '%_user%.createdAt',    attributes: [BROWSE, READ, EDIT] }
        user_updated_at:    { title: Updated At,    field:  '%_user%.updatedAt',    attributes: [BROWSE, READ, EDIT] }
        user_deleted_at:    { title: Deleted At,    field:  '%_user%.deletedAt',    attributes: [BROWSE, READ, EDIT] }
        user_username:      { title: Username,      field:  '%_user%.username',     attributes: [BROWSE, READ, EDIT] }
        user_email:         { title: Email,         field:  '%_user%.email',        attributes: [BROWSE, READ, EDIT] }
        user_enabled:       { title: Enabled,       field:  '%_user%.enabled',      attributes: [BROWSE, READ, EDIT] }
        user_last_login:    { title: Last Login,    field:  '%_user%.lastLogin',    attributes: [BROWSE, READ, EDIT] }
        user_roles:         { title: Roles,         field:  '%_user%.roles',        attributes: [BROWSE, READ, EDIT] }
        user_identity:      { title: Identity,      field:  '%_user%.identity',     attributes: [BROWSE, READ, EDIT] }
        user_identity_uuid: { title: Identity UUID, field:  '%_user%.identityUuid', attributes: [BROWSE, READ, EDIT] }
