services:
    ds_user.service.user:
        class: Ds\Bundle\UserBundle\Service\UserService
        arguments:
            - '@doctrine.orm.entity_manager'
            - Ds\Bundle\UserBundle\Entity\User

    ds_user.filter.user.search:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
                id: exact
                uuid: exact
                username: partial
                email: partial
                identity: exact
                identityUuid: exact
                roles: partial
        tags:
            - { name: api_platform.filter, id: ds.user.search }

    ds_user.filter.user.date:
        parent: api_platform.doctrine.orm.date_filter
        arguments:
            -
                createdAt: ~
                updatedAt: ~
                deletedAt: ~
                lastLogin: ~
        tags:
            - { name: api_platform.filter, id: ds.user.date }

    ds_user.filter.user.boolean:
        parent: api_platform.doctrine.orm.boolean_filter
        arguments:
            -
                enabled: ~
        tags:
            - { name: api_platform.filter, id: ds.user.boolean }
