version: '3.1'

services:
#    db:
#        image: mysql:5.7.21
#        environment:
#            MYSQL_DATABASE: '${DATABASE_NAME}'
#            MYSQL_USER: '${DATABASE_USERNAME}'
#            MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
#            MYSQL_RANDOM_ROOT_PASSWORD: 'true'
#        volumes:
#            - db_data:/var/lib/mysql
#        healthcheck:
#            test: ['CMD-SHELL', 'mysql --user=${DATABASE_USERNAME} --password=${DATABASE_PASSWORD} -e "SHOW TABLES" ${DATABASE_NAME}']
#            interval: 5s
#            timeout: 1s
#            retries: 10

    db:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_DB: '${DATABASE_NAME}'
            POSTGRES_USER: '${DATABASE_USERNAME}'
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
        volumes:
            - db_data:/var/lib/postgresql/data:rw

    php:
        build: .
        depends_on:
            - db
        command: ['wait-for', 'authentication_db:5432', '--timeout=60', '--', 'docker-app-start']
        environment:
            SYMFONY_ENV: dev
        volumes:
            - '${DIRECTORY}:/srv/api-platform'
        secrets:
            - source: jwt_private_key
              target: jwt/key
            - source: jwt_public_key
              target: jwt/key.pub
        links:
              - db:authentication_db
        extra_hosts:
            - 'api.assets.lab.ds:${PROXY_HOST}'
            - 'api.authentication.lab.ds:${PROXY_HOST}'
            - 'api.camunda.lab.ds:${PROXY_HOST}'
            - 'api.cases.lab.ds:${PROXY_HOST}'
            - 'api.cms.lab.ds:${PROXY_HOST}'
            - 'api.discovery.lab.ds:${PROXY_HOST}'
            - 'api.formio.lab.ds:${PROXY_HOST}'
            - 'api.identities.lab.ds:${PROXY_HOST}'
            - 'api.interactions.lab.ds:${PROXY_HOST}'
            - 'api.logs.lab.ds:${PROXY_HOST}'
            - 'api.records.lab.ds:${PROXY_HOST}'
            - 'api.services.lab.ds:${PROXY_HOST}'
            - 'api.tasks.lab.ds:${PROXY_HOST}'
            - 'api.topics.lab.ds:${PROXY_HOST}'

    nginx:
        image: nginx:1.11-alpine
        depends_on:
            - php
        environment:
            - VIRTUAL_HOST
        volumes:
            - '${DIRECTORY}/docker/nginx/conf.d:/etc/nginx/conf.d:ro'
            - '${DIRECTORY}:/srv/api-platform'
        links:
              - php:authentication_php
              - db:authentication_db

volumes:
    db_data:
        driver: local

networks:
    default:
        external:
          name: '${NETWORK}'

secrets:
    jwt_private_key:
        file: '${JWT_PRIVATE_KEY}'
    jwt_public_key:
        file: '${JWT_PUBLIC_KEY}'
