fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  service:
    mailer: 'fos_user.mailer.noop'
  from_email:
    address: admin@localhost
    sender_name: admin
  resetting:
    email:
      template: App:Resetting:email.html.twig
