api:
    resource: .
    type: api_platform

ds_user:
    resource: "@DsUserBundle/Action/"
    type: annotation

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_check:
    path: /login_check
    methods: POST
    defaults: { _controller: FOSUserBundle:Security:check }

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
