api:
    resource: .
    type: api_platform

ds_security:
    resource: '@DsSecurityBundle/Resources/config/routing.yml'

ds_registration:
    resource: '@DsRegistrationBundle/Action/'
    type: annotation

ds_authentication:
    resource: '@DsAuthenticationBundle/Action/'
    type: annotation

ds_authentication_security_check_individual:
    path: /tokens/individual
    methods: POST
    defaults: { _controller: FOSUserBundle:Security:check }

ds_authentication_security_check_staff:
    path: /tokens/staff
    methods: POST
    defaults: { _controller: FOSUserBundle:Security:check }
