api:
    resource: .
    type: api_platform

ds_security:
    resource: '@DsSecurityBundle/Resources/config/routing.yml'

app_action:
    resource: '@AppBundle/Action/'
    type: annotation

app_security_check_individual:
    path: /tokens/individual
    methods: POST
    defaults: { _controller: FOSUserBundle:Security:check }

app_security_check_staff:
    path: /tokens/staff
    methods: POST
    defaults: { _controller: FOSUserBundle:Security:check }
