security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        app_security_provider_anonymous:
            id: app.security.provider.anonymous

        app_security_provider_individual:
            id: app.security.provider.individual

        app_security_provider_staff:
            id: app.security.provider.staff

        app_security_provider_system:
            id: app.security.provider.system

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        security_check_system:
            pattern: ^/tokens/system
            stateless: true
            anonymous: true
            provider: app_security_provider_system
            form_login:
                check_path: app_security_check_system
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        security_check_staff:
            pattern: ^/tokens/staff
            stateless: true
            anonymous: true
            provider: app_security_provider_staff
            form_login:
                check_path: app_security_check_staff
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        security_check_individual:
            pattern: ^/tokens/individual
            stateless: true
            anonymous: true
            provider: app_security_provider_individual
            form_login:
                check_path: app_security_check_individual
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern: ^/
            stateless: true
            anonymous: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/health,               role: IS_AUTHENTICATED_FULLY }
        - { path: ^/permissions,          role: IS_AUTHENTICATED_FULLY }
        - { path: ^/accesses,             role: IS_AUTHENTICATED_FULLY }
        - { path: ^/configs,              role: IS_AUTHENTICATED_FULLY }
        - { path: ^/users,                role: IS_AUTHENTICATED_FULLY }
        - { path: ^/tokens/system,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tokens/staff,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tokens/individual,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/tokens/anonymous,     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration,         role: IS_AUTHENTICATED_ANONYMOUSLY }
