imports:
    - { resource: "../../vendor/digitalstate/core/src/Ds/Component/Entity/Resources/config/event_listener/uuid.yml" }
    - { resource: "../../vendor/digitalstate/core/src/Ds/Component/Security/Resources/config/event_listener/token/ip.yml" }
    - { resource: "../../vendor/digitalstate/core/src/Ds/Component/Security/Resources/config/event_listener/token/client.yml" }
    - { resource: "../../vendor/digitalstate/core/src/Ds/Component/Security/Resources/config/event_listener/token/uuid.yml" }
    - { resource: "../../vendor/digitalstate/core/src/Ds/Component/Security/Resources/config/event_listener/token/identity.yml" }
    - { resource: "../../vendor/digitalstate/core/src/Ds/Component/Security/Resources/config/event_listener/token/validation/client.yml" }

services:
