services:
    ds_authentication.security.provider.anonymous:
        class: Ds\Bundle\AuthenticationBundle\Security\Provider\AnonymousProvider
        arguments:
            - '@fos_user.user_manager'

    ds_authentication.security.provider.individual:
        class: Ds\Bundle\AuthenticationBundle\Security\Provider\IndividualProvider
        arguments:
            - '@fos_user.user_manager'

    ds_authentication.security.provider.staff:
        class: Ds\Bundle\AuthenticationBundle\Security\Provider\StaffProvider
        arguments:
            - '@fos_user.user_manager'

    ds_authentication.security.provider.system:
        class: Ds\Bundle\AuthenticationBundle\Security\Provider\SystemProvider
        arguments:
            - '@fos_user.user_manager'
