objects:
  - key: app.spa.admin
    value: '%config.app.spa.admin.value%'

  - key: app.spa.admin.oauth
    value: '%config.app.spa.admin.oauth.value%'

  - key: app.spa.portal
    value: '%config.app.spa.portal.value%'

  - key: app.spa.portal.oauth
    value: '%config.app.spa.portal.oauth.value%'

  - key: app.registration.individual.owner.type
    value: BusinessUnit

  - key: app.registration.individual.owner.uuid
    value: '%business_unit.administration.uuid%'

  - key: app.registration.individual.data.github
    value: '{}'

  - key: app.registration.individual.data.google
    value: '{}'

  - key: app.registration.individual.data.twitter
    value: '{}'

  - key: app.registration.individual.roles
    value: []

  - key: app.registration.individual.enabled
    value: true

  - key: app.registration.organization.owner.type
    value: BusinessUnit

  - key: app.registration.organization.owner.uuid
    value: '%business_unit.administration.uuid%'

  - key: app.registration.organization.data.github
    value: '{}'

  - key: app.registration.organization.data.google
    value: '{}'

  - key: app.registration.organization.data.twitter
    value: '{}'

  - key: app.registration.organization.roles
    value: []

  - key: app.registration.organization.enabled
    value: true

  - key: app.registration.staff.owner.type
    value: BusinessUnit

  - key: app.registration.staff.owner.uuid
    value: '%business_unit.administration.uuid%'

  - key: app.registration.staff.data.github
    value: '{}'

  - key: app.registration.staff.data.google
    value: '{}'

  - key: app.registration.staff.data.twitter
    value: '{}'

  - key: app.registration.staff.roles
    value: []

  - key: app.registration.staff.enabled
    value: false

  - key: app.resetting.email.subject
    value: app.resetting.email.subject

  - key: app.resetting.email.body.plain
    value: app.resetting.email.body.plain

  - key: app.resetting.email.body.html
    value: app.resetting.email.body.html

prototype:
  owner: BusinessUnit
  owner_uuid: '%business_unit.administration.uuid%'
  key: ~
  value: ~
  tenant: '%tenant.uuid%'
