services:
    app.repository.registration:
        class: AppBundle\Repository\RegistrationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Registration
