services:
    app.service.user:
        class: AppBundle\Service\UserService
        parent: ds_entity.service.entity
        arguments:
            - '@fos_user.user_manager'
            - '@ds_api.api'

    app.service.registration:
        class: AppBundle\Service\RegistrationService
        parent: ds_entity.service.entity
        arguments:
            - '@app.service.user'
            - '@ds_config.service.config'
