services:
    app.service.user:
        class: AppBundle\Service\UserService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@fos_user.user_manager'
            - '@ds_api.factory'
            - '@ds_config.service.config'

    app.service.registration:
        class: AppBundle\Service\RegistrationService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.service.user'
            - '@ds_config.service.config'
