# Routes required to exist by FOSUserBundle, but not used by the application.
fos_user_resetting_check_email:
  methods: GET
  path: /check-email
  defaults: { _controller: FOSUserBundle:Resetting:checkEmail }

fos_user_resetting_reset:
  methods: GET
  path: /reset/{token}
  defaults: { _controller: FOSUserBundle:Resetting:reset }

fos_user_profile_show:
  methods: GET
  path: /profile/show
  defaults: { _controller: FOSUserBundle:Profile:show }

fos_user_security_logout:
  methods: GET
  path: /logout
  defaults: { _controller: FOSUserBundle:Security:logout }
#

app_auth_staff_check:
  methods: POST
  path: /auth/staff
  defaults:
    _controller: FOSUserBundle:Security:check

app_auth_individual_check:
  methods: POST
  path: /auth/individual
  defaults:
    _controller: FOSUserBundle:Security:check

app_auth_organization_check:
  methods: POST
  path: /auth/organization
  defaults:
    _controller: FOSUserBundle:Security:check

app_password_request:
  methods: POST
  path: /password/requests
  defaults:
    _controller: FOSUserBundle:Resetting:sendEmail

app_password_reset:
  methods: POST
  path: /password/reset/{token}
  defaults:
    _controller: FOSUserBundle:Resetting:reset
